### ISSUE TITLE
Kanji composition task is missing some radicals

### ISSUE THREAD

**Issue by btp** [blastrock/kakugo#13]
In the kanji composition activity, some radicals don't show up properly, such as ⺈ for 色 in the screenshot below.

Maybe some more radical entries need to be added to the `dict` database? I noticed that there's no listing for 11912 (⺈).

Thanks again for creating this app!

![Screenshot_20190501-090556](https://user-images.githubusercontent.com/1054948/57058562-80ce2100-6c65-11e9-9be2-2d4ae1073503.png)

**Comment by blastrock** [comment]
What version are you using? This should be fixed in 1.22.On May 2, 2019 08:08, brian pardini <notifications@github.com> wrote:In the kanji composition activity, some radicals don't show up properly, such as ⺈ for 色 in the screenshot below.

Maybe some more radical entries need to be added to the dict database? I noticed that there's no listing for 11912 (⺈).

Thanks again for creating this app!

**Comment by btp** [comment]
Ah, I was on 1.21.4. Just updated to 1.22, and the radicals appear. Thanks!

![Screenshot_20190502-075548](https://user-images.githubusercontent.com/1054948/57084844-e6df9600-6caf-11e9-94a8-3d1715bca470.png)
