### ISSUE TITLE
[feature-request] navigation gestures

### ISSUE THREAD

**Issue by revuwa** [blastrock/kakugo#19]
Would you possibly consider to add some gestures for smoother navigation?

I draw some pics, what came into my mind to show what I mean:
![NaviGestures01](https://user-images.githubusercontent.com/7300276/59864877-07f76580-9388-11e9-8784-9404d409efc1.png)
For example as an optional settings-feature, which enables, that you can swipe to left instead of using the [NEXT] button. Or even better, that it goes to the next challenge automatically, and just stops (and let you swipe or go next) if the previous question was answered wrong.

Such gestures could rearrange the quiz-screen a bit, too:
![NaviGestures02](https://user-images.githubusercontent.com/7300276/59865398-2f026700-9389-11e9-9990-c9ddfbd2c839.png)
The [SURE] and [MAYBE] buttons could be replaced with:
- single tab [SURE]
- double tab OR long press [MAYBE]

What do you think?

**Source / credits:**
The gesture-hands are used/copied from here:
[1] https://www.iconfinder.com/icons/80532/finger_flick_gestureworks_one_icon
[2] https://www.iconfinder.com/icons/80603/double_finger_gestureworks_one_tap_icon
and were slightly modified under the same license: https://creativecommons.org/licenses/by-sa/3.0/us/

**Comment by blastrock** [comment]
Hi,

Thank you for the suggestion! The long press for the "maybe" answer and simple click for "sure" was suggested before, it's on my TO-DO list but I didn't take the time to do it yet. :)

As for the swipe action for "next", that's a good idea too. I am not sure I will be able to do it though. I have tried putting animations between questions and they are very sluggish. I have no idea why since the UI is pretty simple. If there are animations, I want them to be smooth. I have reported the issue to google here https://issuetracker.google.com/issues/132535788 so I can only wait and see for the moment.

I am not fond of going to the next question automatically for the drawing tests because I like to contemplate the kanji after drawing it, it gives me another opportunity to re-memorize it.

**Comment by revuwa** [comment]
> [...] The long press for the "maybe" answer and simple click for "sure" was suggested before, it's on my TO-DO list but I didn't take the time to do it yet. :)

Sorry, I didn't noticed that it was suggested before. Would love to see such a functionality sometime.

> [...] If there are animations, I want them to be smooth. I have reported the issue to google here https://issuetracker.google.com/issues/132535788 so I can only wait and see for the moment.

Don't have a Google-account (to view what's behind that link), but thanks for the info, though.
 
> I am not fond of going to the next question automatically for the drawing tests because I like to contemplate the kanji after drawing it, it gives me another opportunity to re-memorize it.

Hope it's ok, to open this as a seperate topic: https://github.com/blastrock/kakugo/issues/20
