### ISSUE TITLE
[feature-request] pause after wrong answer

### ISSUE THREAD

**Issue by revuwa** [blastrock/kakugo#20]
Allow me to open a seperate issue for the topic, which was only touched lightly in: https://github.com/blastrock/kakugo/issues/19 before.

@blastrock wrote:
> I am not fond of going to the next question automatically for the drawing tests because I like to contemplate the kanji after drawing it, it gives me another opportunity to re-memorize it.

You're absolutely right. So what I imagined was some kind of option for that, like this:
![PauseOnFail](https://user-images.githubusercontent.com/7300276/59922544-4d23a200-9431-11e9-978d-6dcece2c0bb6.png)

I personally more like to get informed, when the answer was wrong only.

Possibly such an option could be combined with with the [SURE] and [MAYBE] switches.
As an example for the theoretical setting: "pause after answering" set to "on fail":
- if you're [SURE] and give the right answer, then the next question would be asked, automatically,
- but if you select [MAYBE] and give (accidentally) the right answer, the correction should be shown, (paused, until [NEXT] would be clicked).

What do you think?

**Comment by blastrock** [comment]
I want to avoid adding more and more settings, it adds more code, and takes longer to test on each release since I have to test all the different configurations.

The long press idea would clean up the test UI by removing buttons and leaving more screen space for the question and answers themselves. I don't think skipping a button click on "next" would bring much to help reviewing the kanji.

**Comment by revuwa** [comment]
I think you're right. 
just wanted to share the idea.
