### ISSUE TITLE
(Another try) German translation

### ISSUE THREAD

**Issue by revuwa** [blastrock/kakugo#72]
The pr: https://github.com/blastrock/kakugo/pull/65 was dropped because kanjidic doesn't have German translations by default.

Meanwhile I contacted the developer of the (proprietary) app [Kanji Study](http://www.kanjistudyapp.com/), and he was so kind to mail me (2883 of) his German kanji-translations for your project wit the words: "If possible, giving credit to Kanji Study would be appreciated."

So I kindly wanted to ask you @blastrock if it would be possible to you with the [file attached](https://github.com/blastrock/kakugo/files/6427496/kanji.zip) to expand your dict-file, or what else should be done for it, please?
But the main question is of course, if you would add German language over this "sideway", (meaning: not officially supported by kanjidic) at all?

Side note: I tried to contact you by (text-only) email for this question, but your host remorseless said: "550 spam detected (in reply to end of DATA command)" to my (well known) German mail hoster. Just fyi ✌️

**Comment by blastrock** [comment]
Hi!

I haven't worked on Kakugo in a while, but since you went out of your way for this, I had to give it a shot.

I have just integrated the file you sent into Kakugo in the [german branch](https://github.com/blastrock/kakugo/tree/german). 2692 of the 3265 kanji now have a German translation, which is more than what I have for French and Spanish. If you could revive #65 with an updated translation, and rebase it on my branch, I can make a release with that. Here is a [diff](https://github.com/blastrock/kakugo/files/6445618/translation.txt) of what changed between your PR and now.

> If possible, giving credit to Kanji Study would be appreciated

I did it in the About section, I'll definitely do it again in the changelog. I need to credit you too, how do you prefer to be named? "revuwa"? Your real name? Something else?

> Side note: I tried to contact you by (text-only) email for this question, but your host remorseless said: "550 spam detected (in reply to end of DATA command)" to my (well known) German mail hoster. Just fyi v

Thank you for the report, I think my mail host really suck, I'll need to find something else.

**Comment by revuwa** [comment]
Sorry for loooong delay. (Wasn't active on GitHub for about a year now for some reasons)...
Created a new [PR](https://github.com/blastrock/kakugo/pull/76), if you like.

PS: I don't need to be credited in any way. Only if you insist to do so, and only 'cause I saw that you're using real names in all of your credits, my name would be: _Moritz Bandemer_

**Comment by revuwa** [comment]
With pleasure:

- The app name: "Kakugo - Learning Japanese"
-> "Kakugo - Japanisch lernen"

- The app description: "Learn Japanese with Kakugo"
-> "Lerne Japanisch mit Kakugo"

Thanks for your cool app and all of your work at all ❤️

**Comment by blastrock** [comment]
The final release is pending, it should be available in a few hours. Thanks again for your work! :)
