### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by FBIAgent05** [blastrock/kakugo#73]
could this app have a function for saving progress by having a backup file

**Comment by jonycoo** [comment]
As far as I know Kakugo support's Android Backup though the native Auto backup, for which you need to enable auto backup in the android settings. You wont see much in your Google drive because they can't be viewed by normal users.
I agree that I would like the ability to use a Backup file.

**Comment by JohelEGP** [comment]
Meanwhile, this works: https://gist.github.com/AnatomicJC/e773dd55ae60ab0b2d6dd2351eb977c1#backup-applications-datas.

**Comment by cleboucher** [comment]
> Meanwhile, this works: https://gist.github.com/AnatomicJC/e773dd55ae60ab0b2d6dd2351eb977c1#backup-applications-datas.

Since Android 12, _android:allowBackup_ is forced to false unless _android:debuggable=true_.
[https://developer.android.com/about/versions/12/behavior-changes-12#adb-backup-restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#adb-backup-restrictions)

Backup and restore through adb don't work anymore.

`> adb -d logcat | grep BackupManagerService
09-08 23:27:26.732   546  1048 V BackupManagerService: [UserID:0] Requesting backup: apks=false obb=false shared=false all=false system=true includekeyvalue=false pkgs=[Ljava.lang.String;@558c2da
09-08 23:27:26.732   546  1048 I BackupManagerService: [UserID:0] Beginning adb backup...
09-08 23:27:26.732   546  1048 D BackupManagerService: [UserID:0] Starting backup confirmation UI, token=981974796
09-08 23:27:26.736   546  1048 D BackupManagerService: [UserID:0] Waiting for backup completion...
09-08 23:27:30.711   546  2424 D BackupManagerService: [UserID:0] acknowledgeAdbBackupOrRestore : token=981974796 allow=true
09-08 23:27:30.711   546  2424 V BackupManagerService: [UserID:0] Acquired wakelock:*backup*-0-1390
09-08 23:27:30.712   546  9749 I BackupManagerService: --- Performing adb backup ---
**09-08 23:27:30.714   546  9749 I BackupManagerService: Package org.kaqui is not eligible for backup, removing.**
09-08 23:27:30.714   546  1048 D BackupManagerService: [UserID:0] Adb backup processing complete.
09-08 23:27:30.715   546  9749 D BackupManagerService: Full backup pass complete.
09-08 23:27:30.716   546  9749 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-1390
 
09-08 23:26:00.254   546  1725 I BackupManagerService: [UserID:0] Beginning restore...
09-08 23:26:00.254   546  1725 D BackupManagerService: [UserID:0] Starting restore confirmation UI, token=1685408779
09-08 23:26:00.259   546  1725 D BackupManagerService: [UserID:0] Waiting for restore completion...
09-08 23:26:04.495   546  4235 D BackupManagerService: [UserID:0] acknowledgeAdbBackupOrRestore : token=1685408779 allow=true
09-08 23:26:04.496   546  4235 V BackupManagerService: [UserID:0] Acquired wakelock:*backup*-0-1390
09-08 23:26:04.496   546  9682 I BackupManagerService: --- Performing full-dataset restore ---
**09-08 23:26:04.500   546  9682 I BackupManagerService: Restore manifest from org.kaqui but allowBackup=false**
09-08 23:26:04.714   546  1725 I BackupManagerService: [UserID:0] adb restore processing complete.
09-08 23:26:04.716   546  9682 D BackupManagerService: Full restore pass complete.
09-08 23:26:04.717   546  9682 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-1390
`

**Comment by JohelEGP** [comment]
That's better fit for the linked gist.
